"""add_teams_and_multi_tenancy

Revision ID: 3edbc464404d
Revises: 7916bc04a105
Create Date: 2025-12-14 01:16:39.678265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edbc464404d'
down_revision: Union[str, None] = '7916bc04a105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('member_limit', sa.Integer(), nullable=True),
    sa.Column('trial_ends_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deletion_scheduled_for', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invitations_email'), 'team_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_team_invitations_token'), 'team_invitations', ['token'], unique=True)
    op.add_column('bed_history', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bed_history', 'teams', ['team_id'], ['id'])
    op.add_column('beds', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'beds', 'teams', ['team_id'], ['id'])
    op.add_column('diagnostics', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'diagnostics', 'teams', ['team_id'], ['id'])
    op.add_column('patients', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'patients', 'teams', ['team_id'], ['id'])
    op.add_column('treatments', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'treatments', 'teams', ['team_id'], ['id'])
    op.add_column('units', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'units', 'teams', ['team_id'], ['id'])
    op.add_column('users', sa.Column('team_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('team_role', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'team_role')
    op.drop_column('users', 'team_id')
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.drop_column('units', 'team_id')
    op.drop_constraint(None, 'treatments', type_='foreignkey')
    op.drop_column('treatments', 'team_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'team_id')
    op.drop_constraint(None, 'diagnostics', type_='foreignkey')
    op.drop_column('diagnostics', 'team_id')
    op.drop_constraint(None, 'beds', type_='foreignkey')
    op.drop_column('beds', 'team_id')
    op.drop_constraint(None, 'bed_history', type_='foreignkey')
    op.drop_column('bed_history', 'team_id')
    op.drop_index(op.f('ix_team_invitations_token'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_email'), table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_table('teams')
    # ### end Alembic commands ###
