"""add_users_and_auth_tracking

Revision ID: 7916bc04a105
Revises: cd23445f8fac
Create Date: 2025-12-13 23:50:31.973787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7916bc04a105'
down_revision: Union[str, None] = 'cd23445f8fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expires', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('diagnostics', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('diagnostics', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('diagnostics', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'diagnostics', 'users', ['created_by_user_id'], ['id'])
    op.add_column('treatments', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'treatments', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatments', type_='foreignkey')
    op.drop_column('treatments', 'created_by_user_id')
    op.drop_constraint(None, 'diagnostics', type_='foreignkey')
    op.drop_column('diagnostics', 'updated_at')
    op.drop_column('diagnostics', 'created_at')
    op.drop_column('diagnostics', 'created_by_user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
