"""add unit bed_number and has_ending_soon_program to patients

Revision ID: cd23445f8fac
Revises: 295b25cb45c8
Create Date: 2025-12-13 20:49:25.092482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd23445f8fac'
down_revision: Union[str, None] = '295b25cb45c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('unit', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('bed_number', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('has_ending_soon_program', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'has_ending_soon_program')
    op.drop_column('patients', 'bed_number')
    op.drop_column('patients', 'unit')
    # ### end Alembic commands ###
